#!/usr/bin/env sh
echo "Begining Post Install setup for SIMLock"
if [ ! -h "/usr/bin/simlock" ]; then
    echo "Creating Symlink in /usr/bin/simlock"
    ln -s /opt/simlock/simlock /usr/bin/simlock
fi
echo "Running SIMLock for the first time"
simlock -d
echo "Post Install setup complete"
